"""testing migration

Revision ID: 0708abcbdeb9
Revises: 3af13ac2d91d
Create Date: 2021-09-28 18:11:14.490593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0708abcbdeb9'
down_revision = '3af13ac2d91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('testing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'testing')
    # ### end Alembic commands ###
