"""added indexes and timestamp

Revision ID: 249c44b10427
Revises: 1cb7b45e771e
Create Date: 2020-12-24 12:03:32.805490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249c44b10427'
down_revision = '1cb7b45e771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_subscribers_first_name'), 'subscribers', ['first_name'], unique=False)
    op.create_index(op.f('ix_subscribers_last_name'), 'subscribers', ['last_name'], unique=False)
    op.create_index(op.f('ix_subscribers_timestamp'), 'subscribers', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_timestamp'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_last_name'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_first_name'), table_name='subscribers')
    op.drop_column('subscribers', 'timestamp')
    # ### end Alembic commands ###
