"""update to str for telegram ids

Revision ID: 29523d50fc1f
Revises: 2acc09ef5e49
Create Date: 2022-02-15 18:49:40.415281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29523d50fc1f'
down_revision = '2acc09ef5e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'telegram_chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'telegram_chat_id',
               existing_type=sa.String(length=60),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
