"""deleted test field

Revision ID: 3af13ac2d91d
Revises: 4088bc4409b5
Create Date: 2021-09-27 13:10:51.539101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3af13ac2d91d"
down_revision = "4088bc4409b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "test_field")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribers",
        sa.Column("test_field", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
