"""untesting migration

Revision ID: 5e5f034037f1
Revises: 0708abcbdeb9
Create Date: 2021-09-28 18:12:49.222974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5f034037f1'
down_revision = '0708abcbdeb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('testing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
