"""updated support_texts field

Revision ID: 7bf20ada100b
Revises: cbaba765195a
Create Date: 2021-01-26 16:06:44.264345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bf20ada100b"
down_revision = "cbaba765195a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribers", sa.Column("number_support_texts", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "number_support_texts")
    # ### end Alembic commands ###
