"""PhishJamsQueue table added

Revision ID: 858bf97db12e
Revises: c33f647ddda8
Create Date: 2021-02-27 19:04:33.396960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858bf97db12e'
down_revision = 'c33f647ddda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phish_jams_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=60), nullable=True),
    sa.Column('platform', sa.String(length=60), nullable=True),
    sa.Column('user_first_name', sa.String(length=60), nullable=True),
    sa.Column('song_name', sa.String(length=60), nullable=True),
    sa.Column('song_url', sa.String(length=60), nullable=True),
    sa.Column('cover_art_url', sa.String(length=60), nullable=True),
    sa.Column('show_date', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phish_jams_queue_timestamp'), 'phish_jams_queue', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phish_jams_queue_timestamp'), table_name='phish_jams_queue')
    op.drop_table('phish_jams_queue')
    # ### end Alembic commands ###
