"""getting mjm table to work

Revision ID: 8f2288d86c45
Revises: a305d93c6238
Create Date: 2021-01-26 18:00:50.389219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f2288d86c45"
down_revision = "a305d93c6238"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mjm_alerts", sa.Column("phone_number", sa.String(length=60), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mjm_alerts", "phone_number")
    # ### end Alembic commands ###
