"""update to str for telegram ids

Revision ID: 95da5c835bf2
Revises: 29523d50fc1f
Create Date: 2022-02-15 18:51:38.683870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95da5c835bf2'
down_revision = '29523d50fc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mjm_alerts', 'telegram_chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mjm_alerts', 'telegram_chat_id',
               existing_type=sa.String(length=60),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
