"""empty message

Revision ID: a2d7cc7f3299
Revises: 858bf97db12e
Create Date: 2021-09-27 12:07:13.657409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2d7cc7f3299"
down_revision = "858bf97db12e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscribers", sa.Column("test", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "test")
    # ### end Alembic commands ###
