"""empty message

Revision ID: b95dcf100347
Revises: 249c44b10427
Create Date: 2020-12-24 12:51:26.937148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b95dcf100347"
down_revision = "249c44b10427"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribers", sa.Column("platform", sa.String(length=60), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "platform")
    # ### end Alembic commands ###
