"""removed json col

Revision ID: c053ad306e89
Revises: 8f2288d86c45
Create Date: 2021-02-07 16:52:24.700801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c053ad306e89'
down_revision = '8f2288d86c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mjm_alerts', 'json_response')
    op.drop_column('subscribers', 'json_response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('json_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mjm_alerts', sa.Column('json_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
