"""Subscribers table

Revision ID: cbaba765195a
Revises: be3c5579d26f
Create Date: 2020-12-30 17:50:30.601182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbaba765195a"
down_revision = "be3c5579d26f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribers", sa.Column("email", sa.String(length=60), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "email")
    # ### end Alembic commands ###
