"""empty message

Revision ID: f96af15f56af
Revises: a2d7cc7f3299
Create Date: 2021-09-27 12:11:07.430869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f96af15f56af"
down_revision = "a2d7cc7f3299"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "test")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribers",
        sa.Column("test", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
